MSG_STORE_NOT_FOUND = "Store not found."
MSG_CHANNEL_TYPE_NOT_FOUND = "Channel type not found."
MSG_PRODUCT_NOT_FOUND = "Product not found."
MSG_PRODUCT_INVALID_FILE_FORMAT = "Invalid file format, only support *.csv"
MSG_PRODUCT_INVALID_FILE_DATA = "Invalid file data, make sure your data order, `name`, `description`, `price`, `stock`"
